[package]
name = "lintel-reporters"
version = "0.0.7"
edition.workspace = true
authors.workspace = true
description = "Reporter implementations for Lintel â€” pretty, text, and GitHub Actions output"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["json-schema", "validation", "linter", "reporter"]
categories = ["development-tools"]

[lints]
workspace = true

[dependencies]
ansi-term-codes = { version = "0.1.0", path = "../ansi-term-codes" }
lintel-validate = { version = "0.0.2", path = "../lintel-validate" }
miette = { version = "7", features = ["fancy"] }
