[package]
name = "lintel-reporters"
version = "0.0.2"
edition.workspace = true
authors.workspace = true
description = "Reporter implementations for Lintel â€” pretty, text, and GitHub Actions output"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["json-schema", "validation", "linter", "reporter"]
categories = ["development-tools"]

[lints]
workspace = true

[dependencies]
lintel-check = { version = "0.0.4", path = "../lintel-check" }
bpaf = { version = "0.9", features = ["derive"] }
humantime = "2"
miette = { version = "7", features = ["fancy"] }
anyhow = "1"
