[package]
name = "npm-release-binaries"
version = "0.0.3"
authors.workspace = true
categories = ["command-line-utilities"]
edition.workspace = true
homepage.workspace = true
keywords = ["npm", "release", "binary", "cli"]
license.workspace = true
repository.workspace = true
description = "Generate and publish platform-specific npm packages from Rust binaries"

[lints]
workspace = true

[dependencies]
bpaf = { workspace = true, features = ["bright-color"] }
flate2 = "1.1.9"
glob.workspace = true
miette = { workspace = true, features = ["fancy"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
tar = "0.4.44"
toml.workspace = true
zip = { version = "8.1.0", default-features = false, features = ["deflate"] }
