output-dir = "./npm-publish"
artifacts-dir = "./artifacts"

[packages.lintel]
name = "@lintel/lintel"
description = "Schema validation for your entire repo"
archive-base-url = "https://github.com/lintel-rs/lintel/releases/download/lintel-v{{version}}"
target-package-name = "@lintel/cli-{{target}}"
readme = "./README.md"
access = "public"

[packages.lintel.targets]
darwin-arm64 = "lintel-aarch64-apple-darwin.tar.gz"
darwin-x64 = "lintel-x86_64-apple-darwin.tar.gz"
linux-arm64 = "lintel-aarch64-unknown-linux-gnu.tar.gz"
linux-arm64-musl = "lintel-aarch64-unknown-linux-musl.tar.gz"
linux-x64 = "lintel-x86_64-unknown-linux-gnu.tar.gz"
linux-x64-musl = "lintel-x86_64-unknown-linux-musl.tar.gz"
win32-x64 = "lintel-x86_64-pc-windows-msvc.zip"
