[project]
name = "lintel"
revision = "1.0"

[profiles.development]
CARGO_REGISTRY_TOKEN = { description = "crates.io API token for publishing releases", required = false }

[profiles.ci]
CARGO_REGISTRY_TOKEN = { description = "crates.io API token for publishing releases", required = true }
