[package]
name = "schema-catalog"
version = "0.0.7"
authors.workspace = true
categories = ["data-structures", "no-std"]
edition.workspace = true
homepage.workspace = true
keywords = ["json-schema", "catalog", "schemastore"]
license.workspace = true
repository.workspace = true
description = "Types for the JSON Schema catalog format (schema-catalog.json)"

[lints]
workspace = true

[dependencies]
glob-set = { version = "0.1.0", path = "../glob-set" }
schemars = { version = "1.2.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.228", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0.149", default-features = false, features = ["alloc"] }
