[package]
name = "schema-catalog"
version = "0.0.5"
authors.workspace = true
categories = ["data-structures"]
edition.workspace = true
homepage.workspace = true
keywords = ["json-schema", "catalog", "schemastore"]
license.workspace = true
repository.workspace = true
description = "Types for the JSON Schema catalog format (schema-catalog.json)"

[lints]
workspace = true

[dependencies]
schemars = { version = "1", default-features = false, features = ["derive"] }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
glob-set = { version = "0.0.1", path = "../glob-set" }
