# $schema: https://raw.githubusercontent.com/lintel-rs/catalog/master/schemas/cargo-toml.json
[package]
name = "lintel-benchmark"
version = "0.0.1"
edition.workspace = true
publish = false

[dependencies]
anyhow = "1"
bpaf = { version = "0.9", features = ["derive", "bright-color"] }
chrono = "0.4"
dirs = "6"
walkdir = "2"

[lints]
workspace = true
