[package]
name = "prettier-json5"
version = "0.1.0"
edition.workspace = true

[dependencies]
prettier-config = { version = "0.1.0", path = "../prettier-config" }
wadler-lindig = { version = "0.1.0", path = "../wadler-lindig" }
anyhow = "1"

[lints]
workspace = true

[dev-dependencies]
prettier-test-harness = { version = "0.1.0", path = "../prettier-test-harness" }
insta = "1"
pretty_assertions = "1"
