[package]
name = "prettier-yaml"
version = "0.1.0"
edition.workspace = true
description = "Prettier-compatible YAML formatter"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
prettier-config = { version = "0.1.0", path = "../prettier-config" }
saphyr-parser = "0.0.6"
anyhow = "1"

[dev-dependencies]
prettier-test-harness = { version = "0.1.0", path = "../prettier-test-harness" }
insta = "1"
pretty_assertions = "1"

[lints]
workspace = true
