[package]
name = "lintel-config-schema-generator"
version = "0.0.3"
edition.workspace = true
authors.workspace = true
description = "Generate JSON Schemas for Lintel configuration files (lintel.toml, lintel-catalog.toml)"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["json-schema", "config", "codegen"]
categories = ["development-tools"]

[lints]
workspace = true

[dependencies]
lintel-config = { version = "0.0.6", path = "../lintel-config" }
lintel-catalog-builder = { version = "0.0.8", path = "../lintel-catalog-builder" }
schema-catalog = { version = "0.0.5", path = "../schema-catalog" }
bpaf = { version = "0.9", features = ["derive"] }
serde_json = "1"
