[package]
name = "lintel-check"
version = "0.0.4"
edition.workspace = true
authors.workspace = true
description = "Core validation engine for Lintel â€” validates JSON, YAML, TOML, JSON5, and JSONC against JSON Schema"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["json-schema", "validation", "yaml", "toml", "linter"]
categories = ["development-tools"]

[dependencies]
lintel-config = { version = "0.0.3", path = "../lintel-config" }
lintel-http-cache = { version = "0.0.4", path = "../lintel-http-cache" }
lintel-validation-cache = { version = "0.0.3", path = "../lintel-validation-cache" }
jsonschema = { version = "0.42", features = ["resolve-async"] }
tokio = { version = "1", features = ["rt", "fs"] }
glob = "0.3"
glob-match = "0.2"
serde_json = "1"
anyhow = "1"
serde_yaml = "0.9"
miette = { version = "7", features = ["fancy"] }
thiserror = "2"
json5 = "1.3"
jsonc-parser = { version = "0.29", features = ["serde"] }
ignore = "0.4"
toml = "1.0"
schemastore = { version = "0.0.4", path = "../schemastore" }
tracing = "0.1"

[build-dependencies]
lintel-config = { version = "0.0.3", path = "../lintel-config" }
serde_json = "1"

[lints]
workspace = true

[dev-dependencies]
insta = { version = "1", features = ["filters"] }
tempfile = "3"
tokio = { version = "1", features = ["rt", "macros"] }
