[package]
name = "lintel-check"
version = "0.0.12"
edition.workspace = true
authors.workspace = true
description = "Check command for Lintel â€” runs schema validation and additional checks"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["json-schema", "validation", "yaml", "toml", "linter"]
categories = ["development-tools"]

[lints]
workspace = true

[dependencies]
lintel-validate = { version = "0.0.5", path = "../lintel-validate" }
lintel-format = { version = "0.0.1", path = "../lintel-format" }
bpaf = { version = "0.9", features = ["derive"] }
anyhow = "1"
miette = "7"
