# $schema: https://raw.githubusercontent.com/lintel-rs/catalog/master/schemas/cargo-toml.json
[package]
name = "lintel-github-action"
version = "0.0.2"
edition.workspace = true
authors.workspace = true
description = "GitHub Action binary for Lintel â€” creates Check Runs with inline annotations"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["json-schema", "validation", "github-action", "linter"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
lintel-check = { version = "0.0.3", path = "../lintel-check" }
lintel-reporters = { version = "0.0.2", path = "../lintel-reporters" }
bpaf = { version = "0.9", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lints]
workspace = true
