[package]
name = "prettier-markdown"
version = "0.1.0"
edition.workspace = true
description = "Prettier-compatible Markdown formatter"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
prettier-config = { version = "0.1.0", path = "../prettier-config" }
prettier-jsonc = { version = "0.1.0", path = "../prettier-jsonc" }
prettier-json5 = { version = "0.1.0", path = "../prettier-json5" }
prettier-yaml = { version = "0.1.0", path = "../prettier-yaml" }
wadler-lindig = { version = "0.1.0", path = "../wadler-lindig" }
comrak = { version = "0.36", default-features = false }
taplo.workspace = true
unicode-width = "0.2"
anyhow = "1"

[dev-dependencies]
prettier-test-harness = { version = "0.1.0", path = "../prettier-test-harness" }
insta = "1"
pretty_assertions = "1"

[lints]
workspace = true
