[package]
name = "prettier-jsonc"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
json5 = "0.4"
jsonc-parser = { version = "0.24", features = ["serde"] }
glob-match = "0.2"
anyhow = "1"

[lints]
workspace = true

[dev-dependencies]
insta = "1"
pretty_assertions = "1"
