[package]
name = "wadler-lindig"
version = "0.1.0"
edition.workspace = true
description = "Wadler-Lindig pretty-printing algorithm"
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
prettier-config = { version = "0.1.0", path = "../prettier-config" }

[lints]
workspace = true
