[package]
name = "wadler-lindig"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description = "Wadler-Lindig pretty-printing algorithm"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["pretty-printing", "formatting", "wadler-lindig"]
categories = ["text-processing", "algorithms"]

[lints]
workspace = true

[dependencies]
prettier-config = { version = "0.1.0", path = "../prettier-config" }
