[package]
name = "lintel-identify"
version = "0.0.8"
authors.workspace = true
categories = ["development-tools"]
edition.workspace = true
homepage.workspace = true
keywords = ["json-schema", "validation", "identification", "linter"]
license.workspace = true
repository.workspace = true
description = "Schema identification for JSON and YAML files using JSON Schema"

[lints]
workspace = true

[dependencies]
anyhow = "1"
bpaf = { version = "0.9", features = ["derive"] }
glob-match = "0.2"
jsonschema-explain = { version = "0.2.3", path = "../jsonschema-explain" }
lintel-cli-common = { version = "0.0.4", path = "../lintel-cli-common" }
lintel-config = { version = "0.0.6", path = "../lintel-config" }
lintel-schema-cache = { version = "0.0.10", path = "../lintel-schema-cache" }
lintel-validate = { version = "0.0.5", path = "../lintel-validate" }
schemastore = { version = "0.0.9", path = "../schemastore" }
serde_json = "1"
terminal_size = "0.4"
tracing = "0.1"
