[package]
name = "lintel-identify"
version = "0.0.6"
edition.workspace = true
authors.workspace = true
description = "Schema identification for JSON and YAML files using JSON Schema"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["json-schema", "validation", "identification", "linter"]
categories = ["development-tools"]

[lints]
workspace = true

[dependencies]
lintel-config = { version = "0.0.5", path = "../lintel-config" }
lintel-schema-cache = { version = "0.0.8", path = "../lintel-schema-cache" }
lintel-validate = { version = "0.0.3", path = "../lintel-validate" }
lintel-cli-common = { version = "0.0.3", path = "../lintel-cli-common" }
schemastore = { version = "0.0.8", path = "../schemastore" }
jsonschema-explain = { version = "0.2.2", path = "../jsonschema-explain" }
bpaf = { version = "0.9", features = ["derive"] }
glob-match = "0.2"
anyhow = "1"
serde_json = "1"
tracing = "0.1"
terminal_size = "0.4"
