[package]
name = "prettier-config"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
serde_yaml = "0.9"
json5 = "0.4"
toml = "1.0"
glob-match = "0.2"
anyhow = "1"

[lints]
workspace = true
