[package]
name = "lintel"
version = "0.0.2"
edition.workspace = true
authors = ["Ian Macalinao <me@ianm.com>"]
description = "Validate JSON and YAML files against JSON Schema"
license = "Apache-2.0"
repository = "https://github.com/lintel-rs/lintel"
homepage = "https://github.com/lintel-rs/lintel"
keywords = ["json-schema", "validation", "yaml", "linter", "cli"]
categories = ["command-line-utilities", "development-tools"]
readme = "../../README.md"

[dependencies]
lintel-check = { version = "0.0.2", path = "../lintel-check" }
bpaf = { version = "0.9", features = ["derive", "bright-color"] }
humantime = "2"
miette = { version = "7", features = ["fancy"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1"
serde_json = "1"
serde_yaml = "0.9"
toml = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-tree = "0.4"

[lints]
workspace = true

[dev-dependencies]
insta = { version = "1", features = ["filters"] }
