[package]
name = "lintel"
version = "0.0.3"
edition.workspace = true
authors.workspace = true
description = "Validate JSON and YAML files against JSON Schema"
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords = ["json-schema", "validation", "yaml", "linter", "cli"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
jsonschema-explain = { version = "0.1.0", path = "../jsonschema-explain" }
lintel-annotate = { version = "0.0.3", path = "../lintel-annotate" }
lintel-check = { version = "0.0.4", path = "../lintel-check" }
lintel-reporters = { version = "0.0.2", path = "../lintel-reporters" }
schemastore = { version = "0.0.3", path = "../schemastore" }
bpaf = { version = "0.9", features = ["autocomplete", "derive", "bright-color"] }
glob-match = "0.2"
humantime = "2"
miette = { version = "7", features = ["fancy"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1"
serde_json = "1"
serde_yaml = "0.9"
toml = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-tree = "0.4"

[lints]
workspace = true

[dev-dependencies]
insta = { version = "1", features = ["filters"] }
